proxy:
    solr:
        servlet_url: /proxy/*
        target_url: http://localhost:8008/solr/

    replacer:
        servlet_url: /contentreplacer/*
        target_url: http://localhost:8008/replace/
        url_to_replace: http://some.internal.server/solr/
        url_replacement_value: http://localhost:8008/contentreplacer/


server:
    port: 8008

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false